version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: repasse_veiculos_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: repasse_veiculos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 